### ISSUE TITLE
Make an UI for offline users.

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#193]
Not all users are `logged_in`. So we need to make something for them too.

Address the components in the following images

![image](https://github.com/Tokito69/CoreProject-V3-UI/assets/61817579/1b7437d4-8172-4f7f-80de-bdc60017f537)
![image](https://github.com/Tokito69/CoreProject-V3-UI/assets/61817579/314393af-89fb-4428-889e-8d55854993ce)

**Comment by tokitou-san** [comment]
![Screenshot from 2023-05-29 08-47-47](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/4dd5ca54-6fe6-483e-9aad-aa46b0a8ad59)
And also this section (__My List__) needs to:
