### ISSUE TITLE
Remove arbitrary values and convert it to tailwind compatible class

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#200]
https://github.com/Tokito69/CoreProject-V3-UI/blob/0a8cbc2f678aedc02d21910348cfaec6bc608556/src/lib/icons/core_project.svelte#L2-L7

**Comment by baseplate-admin** [comment]
`"text-[#dcd9f7]"` is arbitrary.

Convert it to one of tailwind specific classes.

**Comment by Tokito69** [comment]
> "text-[#dcd9f7]" is arbitrary.

Why did you do that, okay will fix that LOL
