### ISSUE TITLE
imgbox is not working

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#203]
![image](https://github.com/Tokito69/CoreProject-V3-UI/assets/61817579/63fcae89-3df2-4dcf-bb02-ca80324d6e4e)

**Comment by Tokito69** [comment]
Okay I've no issue with that, so imgbox wont work for you?
Alright :)

**Comment by baseplate-admin** [comment]
Just use github for things.
