### ISSUE TITLE
add this type of navbar?

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#204]
![image](https://github.com/Tokito69/CoreProject-V3-UI/assets/61817579/d49fbe3e-27f8-4fd2-874d-87681bb0d103)

Source : https://www.figma.com/file/tNUUtsk20ltOrQICdEoggG/Core-Project?type=design&node-id=975-1859&t=tlafIQVXAUQd2UcL-0

**Comment by Tokito69** [comment]
Yep, thats a cool design, but lack some options.
We can do this later? or if you want...

**Comment by baseplate-admin** [comment]
<blockquote>
 We can do this later.. Yes sure. But <b><code>anime_info</code></b> ui should not have a large search form ( if user navigates to that page )

</blockquote>

**Comment by tokitou-san** [comment]
Info page card has options that we want, including "download"

![Screenshot from 2023-07-12 10-02-05](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/a4d82e57-2688-449f-828c-c5cbe87488d8)

**Comment by baseplate-admin** [comment]
🗿
