### ISSUE TITLE
Profile dropdown overflow issue

### ISSUE THREAD

**Issue by tokitou-san** [tokitou-san/CoreProject-V3-UI#207]
![Screenshot from 2023-05-28 19-59-45](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/205bf281-4f91-4b5d-9848-c28d3da146e2)

**Comment by baseplate-admin** [comment]
https://stackoverflow.com/a/62554812

**Comment by baseplate-admin** [comment]
Hey i can code ATM. Did you fix it?
