### ISSUE TITLE
Layout breaks at 220% zoom

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#224]
![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/aa400a97-5d89-429a-8c20-424305a61100)

**Comment by tokitou-san** [comment]
Yea, this will be fixed along with making info page responsive.

**Comment by baseplate-admin** [comment]
![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/1c937fcf-5be5-4f21-b271-09879d7b1da7)

Home page does the same on 250% zoom

**Comment by tokitou-san** [comment]
> Home page does the same on 250% zoom

Yea, whats the problem? Its mobile layout

**Comment by baseplate-admin** [comment]
Mobile layout on PC screen

**Comment by tokitou-san** [comment]
> Mobile layout on PC screen

Yea, try zooming github

**Comment by baseplate-admin** [comment]
> Yea, try zooming github

Try zooming games lol

**Comment by tokitou-san** [comment]
> Try zooming games lol

Try zooming any websites -_________- not games

**Comment by baseplate-admin** [comment]
> Try zooming any websites -_________- not games

Try zooming on sora amamiya
