### ISSUE TITLE
BG cover overflows at 130% zoom

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#225]
![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/95e3a71e-2740-4b84-8e45-c7b0b0b5b82a)

See two scrollbars?

**Comment by baseplate-admin** [comment]
![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/3418dc0a-1ea2-474f-85be-fc97f8bc1f8f)

**Comment by tokitou-san** [comment]
Why such things happening in your screen, I've got no problems even with higher zoom.

**Comment by baseplate-admin** [comment]
130% of 1080p 

Do the math :)
