### ISSUE TITLE
Star rating component size looks off

### ISSUE THREAD

**Issue by tokitou-san** [tokitou-san/CoreProject-V3-UI#226]
![Screenshot from 2023-06-02 20-55-55](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/c33408dc-5703-4374-afc8-45aed28f2108)

This lib only supports pixel values ( cant use "vw" measures )

**Comment by baseplate-admin** [comment]
https://css-tricks.com/fractional-svg-stars-with-css/

**Comment by baseplate-admin** [comment]
This is unnecessary. As things looks fine to me

**Comment by baseplate-admin** [comment]
https://github.com/skeletonlabs/skeleton/pull/1654

**Comment by baseplate-admin** [comment]
I am taking THIS

**Comment by tokitou-san** [comment]
> I am taking THIS

But **Hoshino** is mine :heart:
