### ISSUE TITLE
Login page needs a skeleton

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#237]
https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/acb3d8c4-75c2-409a-b696-40ecbadcaf62

The hyouka issue is fixed but the login page issue is still there

**Comment by baseplate-admin** [comment]
i can work on this if you want

**Comment by tokitou-san** [comment]
> i can work on this if you want

Sorry for late response
Ya I've no problem, lmk your decision

**Comment by baseplate-admin** [comment]
>  Ya I've no problem, lmk your decision

Took too long. Will work tomorrow
