### ISSUE TITLE
Remake the comment section

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#239]
Instead of doing what we are doing atm we can use 

Target : 
 
![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/df9c9f6a-b6e6-48f2-8a17-c151c1839fbd)

---

Instead of what we are doing right now, we can use

1. [`marked`](https://github.com/markedjs/marked) + [`marked-emoji`](https://github.com/UziTech/marked-emoji)
    
      Pros : 
      - We dont have to do anything too complex
      - Works great with markdown
      
      Cons : 
      - We have to make our own comment section

2. [`quill`](https://github.com/quilljs/quill/) + [`quill-emoji`](https://github.com/contentco/quill-emoji)

**I dont know how this works at all.**

3. [`lexical`](https://github.com/facebook/lexical)

**Another Facebook product**

4. Going custom.
    
      Pros : 
      - We can fine tune it to our requirement
      
      Cons : 
      - We need to code everything. About 75% of the functionality is already present.

**Comment by baseplate-admin** [comment]
if we choose custom, we need to have image upload functionality. 

Look into [`skeleton file dropzone`](https://www.skeleton.dev/components/file-dropzone)

**Comment by baseplate-admin** [comment]
TBH i think we should go with custom option

**Comment by tokitou-san** [comment]
@baseplate-admin Thanks for explaining :)
> TBH i think we should go with custom option

Yeah I think so, It would be a great experience and what about adding stickers options instead emoji picker ( or separate ).

> if we choose custom, we need to have image upload functionality.
Look into [skeleton file dropzone](https://www.skeleton.dev/components/file-dropzone)
we also need a preview section. ( like how github does it, along with the tooltips )

Yea and also with image links, what you meant by _"along with the tooltips"_ ( github preview section has tooltips? )

### **Other Features**
A **spoiler** option, which is basically a checkbox
If a comment is spoiler, shows a spoiler alert on top of that comment box ( background blurred ) then other users can see if they wanna see spoiler.

And that **stickers** options that I mentioned before

**Comment by baseplate-admin** [comment]
Done
