### ISSUE TITLE
Pixelated/Blurred header logo

### ISSUE THREAD

**Issue by tokitou-san** [tokitou-san/CoreProject-V3-UI#263]
Header logo seems like **pixelated/blurred**
Maybe **_a_** tag causing problem
Looks fine on hovering

[Screencast from 2023-06-09 21-33-58.webm](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/395371f9-3ec6-455d-b217-ebc2f41a41ad)

**Comment by tokitou-san** [comment]
fukku
fukku

**Comment by tokitou-san** [comment]
fukku
fukku
fukku
fukku

**Comment by baseplate-admin** [comment]
This is due to png to svg conversion

**Comment by tokitou-san** [comment]
> This is due to png to svg conversion  

Cant we make the same thing like we did for "coreproject" logo?

**Comment by baseplate-admin** [comment]
Look at the `I`, in anime core

**Comment by baseplate-admin** [comment]
This is due to color change.. everything is ok on our end
