### ISSUE TITLE
Add Image loader for `/user/`

### ISSUE THREAD

**Issue by tokitou-san** [tokitou-san/CoreProject-V3-UI#272]
Add ImageLoader instead this:
```html
<div
    class="h-full w-full bg-cover bg-center bg-no-repeat"
    style="background-image: url('{item.cover ?? ''}')"
/>
```

**Comment by vishalpawarR** [comment]
@tokitou-san Please provide proper screenshot and explanations here. May be I can help you with this.

**Comment by tokitou-san** [comment]
@vishalpawarR Hey there! sorry for the late response.

The issue is: first check [this](https://v3.coreproject.moe/user/login)

look at the loading behavior of image on left ( not lazy loading )
and look at that forms when loading ( shows a placeholder )

we need to add this thing to image as well.
can do simply with [ImageLoader](https://github.com/tokitou-san/CoreProject-V3-UI/blob/master/src/lib/components/shared/image/image_loader.svelte) module
[Example](https://github.com/tokitou-san/CoreProject-V3-UI/blob/a8756670ff37127fb71dc5aab68809987c522e6a/src/lib/components/pages/anime_info/anime_main_details.svelte#L91-L95)

lmk if you've any doubts :)

**Comment by tokitou-san** [comment]
@vishalpawarR Hey are you working on this?
or I can do this, its almost time :P

**Comment by baseplate-admin** [comment]
Give him a bit of time. We will swing back to this tomorrow :)
