### ISSUE TITLE
Editor emoji position not correct

### ISSUE THREAD

**Issue by tokitou-san** [tokitou-san/CoreProject-V3-UI#291]
Emoji picker appears in a wrong position.
Probably because of some calculation problems with `caret-pos` lib.
[Here we go](https://github.com/tokitou-san/CoreProject-V3-UI/blob/3f18ea639f047e2eb325e43c25a4fc81a05ddaab/src/lib/components/shared/text_editor.svelte#LL432C39-L432C39)

![Screenshot from 2023-06-17 00-07-02](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/821524f1-5659-48b1-9ad3-204da7a44f23)

**Comment by baseplate-admin** [comment]
This should be of help

https://codingbeautydev.com/blog/javascript-get-mouse-position/

**Comment by baseplate-admin** [comment]
https://github.com/deshiknaves/caret-pos/issues/53#issue-1590378950

**Comment by baseplate-admin** [comment]
https://stackoverflow.com/a/61213870

**Comment by baseplate-admin** [comment]
tracking : 
* https://github.com/floating-ui/floating-ui/discussions/2406

**Comment by baseplate-admin** [comment]
@tokitou-san , use https://www.npmjs.com/package/@koddsson/textarea-caret. Github uses this
![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/313ffabb-ae5b-41b7-845e-d40bc09ae248)
