### ISSUE TITLE
Redesign search panel

### ISSUE THREAD

**Issue by tokitou-san** [tokitou-san/CoreProject-V3-UI#302]
Current search panel has many other non useful components.
I'm thinking about removing those and instead add other search options like genres, etc...

![Screenshot from 2023-06-18 01-54-38](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/11d0ae7b-4dda-469a-a1b4-b9d1c71341b0)

**Comment by baseplate-admin** [comment]
I am against this.

Instead of customizing the search panel we should make an explore page with more options
