### ISSUE TITLE
Don't modify the document. If you need to store the referance, keep it inside some js array.

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#313]
https://github.com/tokitou-san/CoreProject-V3-UI/blob/4ba4b7a08a350ee3f3c7c69e5f0584a3c261dc98/src/lib/components/pages/anime_info/index.svelte#L120

**Comment by tokitou-san** [comment]
> Don't modify the document. If you need to store the referance, keep it inside some js array.

Okay, I think this one will be solved when recreating with tailwind
