### ISSUE TITLE
Width issue

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#321]
![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/2594eb8b-c8ab-48a3-a5b0-d7b6e71b60ff)

![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/2e7f71dc-146e-4fce-bf35-0c051d63830c)

**Comment by tokitou-san** [comment]
Yes its a drag
I think we need to change its layout/design
I made a layout check :)

![Screen Shot 2023-06-22 at 10 47 21](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/96485c1e-18ea-4495-b905-bbcc8ed02092)

```let x = "position";```

^^^^ we can align items to start, if you dont like center {x}
and if we choose center {x}, we can also make that synopsis thing center ( looks good with center {x} )

**Comment by baseplate-admin** [comment]
> ^^^^ we can align items to start, if you dont like center {x}

this image has contrast issues :|

That's why i am against this :)

**Comment by tokitou-san** [comment]
Why added `w-screen` ? LOL that's why it overflowed
https://github.com/tokitou-san/CoreProject-V3-UI/blob/8fdbc3ba5be99323922337b3eedae74d48af9386/src/lib/components/pages/anime_info/index.svelte#L124

**Comment by baseplate-admin** [comment]
May god help you. Child

**Comment by tokitou-san** [comment]
> May god help you. Child

Ehh what? I'm I wrong?
