### ISSUE TITLE
Add ScrollArea for synopsis in slider

### ISSUE THREAD

**Issue by tokitou-san** [tokitou-san/CoreProject-V3-UI#328]
Add a scroll_area instead showing ellipsis.
What you think?

![Screenshot from 2023-06-22 21-08-51](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/8a9964cf-076b-41ab-8522-f711f008eb81)

**Comment by baseplate-admin** [comment]
Wait this wasnt implemented?

**Comment by tokitou-san** [comment]
> Wait this wasnt implemented?

LOL Unfortunately no ...
