### ISSUE TITLE
Make a page for entries that doesn't exist

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#338]
Take for example i visit `/mal/2/` 

There's no entry for myanimelist item 2.

![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/001ad733-683c-4ec4-9646-a1ec53a9552f)

make something that tells user that the entry is not available.

**Comment by tokitou-san** [comment]
> make something that tells user that the entry is not available.

This is good: from v2
![Screenshot from 2023-06-24 20-53-54](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/a45d7e13-73ca-4d70-a030-e0cf22bb0fe3)

**Comment by baseplate-admin** [comment]
This looks busta straight busta to me

**Comment by baseplate-admin** [comment]
we need something fancy

**Comment by tokitou-san** [comment]
> we need something fancy

What about  a tattoo like design? sounds cool :D

**Comment by baseplate-admin** [comment]
you do it
