### ISSUE TITLE
Type issue for `tippy.js`

### ISSUE THREAD

**Issue by tokitou-san** [tokitou-san/CoreProject-V3-UI#353]
![Screenshot from 2023-06-28 02-13-27](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/21ad4a97-427c-4687-b1b3-328b5b747df4)

**Comment by baseplate-admin** [comment]
Take another swing at skeleton dropdown

**Comment by baseplate-admin** [comment]
Leave it to me :)

**Comment by baseplate-admin** [comment]
This issue is due to how svelte 4 interprets everything as custom component
