### ISSUE TITLE
feat: lights On/Off functionality

### ISSUE THREAD

**Issue by tokitou-san** [tokitou-san/CoreProject-V3-UI#380]
![Screenshot from 2023-07-02 16-13-47](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/598f90cd-9b00-4091-83b2-731719b4cc21)

**Comment by tokitou-san** [comment]
@baseplate-admin We need this functionality in episode page.
Which adds a overlay over window with a dark background and with an opacity, like `bg-surface-900/90`
but it shouldnt affect video player.

To get this, I think we can play with some index, add higher index to video player and `relative` class.
then a if else logic for the overlay to show and hide.

Uhh you've any other ideas in mind?

**Comment by baseplate-admin** [comment]
Uhh i still dont get you.

Overlay over window with dark background?

**Comment by tokitou-san** [comment]
>Uhh i still dont get you.
Overlay over window with dark background?

Okay check this site?
https://sanji.to/watch/one-piece-movie-1-3096?ep=58122

![Screenshot from 2023-07-02 19-13-41](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/0208a02f-1ecc-4a80-b4fd-dee495728d17)
_click on that light button and see what happens_
