### ISSUE TITLE
404 page has inherint issues

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#382]
![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/3998ad92-b7bb-4435-9212-0b677c8d8c5a)

**Comment by baseplate-admin** [comment]
This issue is due the gradient overflowing the div

**Comment by baseplate-admin** [comment]
do we want to render on canvas?

**Comment by tokitou-san** [comment]
@baseplate-admin 
I made a [PR](https://github.com/tokitou-san/CoreProject-V3-UI/pull/400)

Now I'm thinking that, what about changing 404 page layout?
place an image with background instead a transparent one...
and position absolute the contents

Uhh like we did in `/user/` path ( left side )
What you feel

**Comment by baseplate-admin** [comment]
I feel like we have created something cool and we are going to lose it due to how css operates :|
