### ISSUE TITLE
Upload page has inherint issues

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#431]
![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/ce1f6055-7778-46f0-90de-ae16a6c99e90)

**Comment by baseplate-admin** [comment]
why is this the case

**Comment by baseplate-admin** [comment]
https://github.com/tokitou-san/CoreProject-V3-UI/blob/27552d0cf0bce4c6bcf2c21cb9d602fe4b24f864/src/routes/upload/%2Bpage.svelte#L22-L24

Should be fixed once we add login page

**Comment by tokitou-san** [comment]
> Should be fixed once we add login page

Not upload page skeleton?
then show login dialog?

**Comment by baseplate-admin** [comment]
Just add login page. the issue you see is currently is due to await block

**Comment by tokitou-san** [comment]
> the issue you see is currently is due to await block

We validate token... if that token is not valid... shows login page...
while validating... shows skeleton... if its valid... shows upload page...
no?

>Just add login page.

it shows every time upload page loads?
and why its to be a page? its better to be a dialog/modal?

**Comment by baseplate-admin** [comment]
I will explain in a bit. Currently am tired
