### ISSUE TITLE
Remove image mask

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#482]
https://github.com/tokitou-san/CoreProject-V3-UI/blob/c4ce2ab28d371525577c50f458380635b07e5d63/src/lib/components/shared/scroll_area.svelte#L64-L75

use the approach Daisy Ui did https://daisyui.com/components/button/

**Comment by tokitou-san** [comment]
> use the approach Daisy Ui did 

LOL thats a hacky way... yea lgtm
