### ISSUE TITLE
There's a small problem with `markdown` renderer

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#526]
![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/5ed65a83-176f-4809-9bf7-a4eab91cde1e)

**Comment by baseplate-admin** [comment]
![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/5e273702-eec3-4bd1-b073-6ad7fce0abb7)

**Comment by tokitou-san** [comment]
Okay... when this happens?
actually the whole code block design looks off

**Comment by baseplate-admin** [comment]
Yea?
Take a look
