### ISSUE TITLE
Change UI for explore Page

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#591]
![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/a33e5b4f-f3fe-4848-9111-f8425d1634cb)

I like this UI

Link : https://anilist.co/search/anime/popular

**Comment by tokitou-san** [comment]
Yeah, also do we need something like this ( option for changing layout )
![Screenshot from 2023-08-19 05-27-42](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/1a14744d-d348-4f77-8f48-ad87be260d80)

I also like this design...
1. No need tippy
2. can do hover effect like we did in episode page
3. can add scroll effect for genres boxs
umm yea overall better it seems

**Comment by baseplate-admin** [comment]
> Yeah, also do we need something like this ( option for changing layout )

This actually sounds better to me NGL. Giving more options is always better 😉
