### ISSUE TITLE
Add `ImageLoader` here

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#608]
![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/a15d745d-54e3-41f8-ad9f-9a7c8caaf970)

**Comment by tokitou-san** [comment]
Already did.

![Screenshot from 2023-08-20 05-14-19](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/e8099241-f884-4399-989c-dff710ebaa76)
