### ISSUE TITLE
Change Color of genres in `anime_info` page

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#609]
![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/1432e1d9-94b0-4faf-aa9f-ff2e6a7f7da9)

**Comment by girish-07** [comment]
Would like to know more about this issue. Should each genres be assigned particular colours to distinguish them?

**Comment by tokitou-san** [comment]
> Would like to know more about this issue.

Hi @girish-07, appreciate your interest on this.
So basically this is a very small issue uhh cant consider as an issue lol.
Just change the background color of genres boxes from that dark color to a brighter one.

>Should each genres be assigned particular colours to distinguish them?

Nah, later we add each color for these genres boxes ( not for each genre ) of each animes.
For now add a color eg. `warning-400`, `primary-500`, `surface-50`, something like that...

If you want to work on this, I would recommend to take a look at `theme.scss` file.
Lmk if you've any doubts. good day!

**Comment by girish-07** [comment]
Okay, I will work on this issue
