### ISSUE TITLE
explore page has gradient issues

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#628]
![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/ac333cb7-d9ef-47a5-9211-e260c42112ee)

**Comment by tokitou-san** [comment]
Whats the issue? cant you read?

**Comment by baseplate-admin** [comment]
Problem is when scrolled to bottom there should be no gradient

**Comment by tokitou-san** [comment]
> Problem is when scrolled to bottom there should be no gradient

Okay I get it, but which way you think is better?

- Use js to add `mask-bottom`
- Add a bit more `pb`

**Comment by baseplate-admin** [comment]
> Use `js` to add mask-bottom

This
