### ISSUE TITLE
Design Homepage

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#642]
We should design a landing page

**Comment by baseplate-admin** [comment]
https://squidfunk.github.io/mkdocs-material/

**Comment by tokitou-san** [comment]
Okay what you mean? Landing page for what?
for CoreProject ( main )?

**Comment by baseplate-admin** [comment]
>  for CoreProject ( main )?

Correct

**Comment by tokitou-san** [comment]
Do we need to think about this RN?
instead we can design other pages, its better I think

**Comment by baseplate-admin** [comment]
>  instead we can design other pages, its better I think

If we have more than one project, its better to think now.

**Comment by tokitou-san** [comment]
> If we have more than one project, its better to think now.

Indeed, we need to discuss about the structure of web.
like if we add api docs inside other features

Also I think its better to move this to a discussion or main REPO

**Comment by baseplate-admin** [comment]
> Indeed, we need to discuss about the structure of web.

Yep. 

>  like if we add api docs inside other features

Look at tonapi.io


> Also I think its better to move this to a discussion or main REPO

No this is fine in this issue

**Comment by baseplate-admin** [comment]
https://michalsnik.github.io/aos/
