### ISSUE TITLE
This code is not working

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#659]
https://github.com/tokitou-san/CoreProject-V3-UI/blob/a4490b1d7371a727e79bc63766e7513380487e16/src/routes/%2Bpage.svelte#L170-L181

**Comment by tokitou-san** [comment]
It works, whats the issue :confused: 
recently your issues are being unclear, please explain this a bit or provide a video or something like.

**Comment by baseplate-admin** [comment]
> please explain this a bit or provide a video

**Comment by baseplate-admin** [comment]
[screen-recorder-wed-aug-30-2023-22-16-48.webm](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/e047fd67-6546-48d6-b759-2780da962e44)

**Comment by baseplate-admin** [comment]
See the timer still ticking?

that should not be the case

**Comment by tokitou-san** [comment]
> See the timer still ticking? that should not be the case

Actually no, it works fine.
You can barely see because we used `tweened` to tween values.
```js
let progress_value = 0,
    tweened_progress_value = tweened(progress_value);
$: tweened_progress_value.set(progress_value);
```
First I thought same, but take a close look? it stops after going out of viewport, and starts slowly.

**Comment by baseplate-admin** [comment]
> that should not be the case

Are you sure about closing this? In my opinion the timer shouldn't tick if the image is not fully visible..

**Comment by tokitou-san** [comment]
> In my opinion the timer shouldn't tick if the image is not fully visible..

Okay, then we need to add a `threshold` value of
`0.5` sounds good?

**Comment by baseplate-admin** [comment]
>   0.5 sounds good?

Stop when we cover 80% of image
