### ISSUE TITLE
The middle section scroll logic is not working for last 2 elements

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#660]
![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/898f0630-cc6f-45a8-afc9-18c76f2c5012)

**Comment by tokitou-san** [comment]
No? but it works in my end.
also provide a video instead image since this is related to animation.

**Comment by baseplate-admin** [comment]
[screen-recorder-wed-aug-30-2023-22-15-59.webm](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/6d148f3b-ae89-499a-a96b-fe42e21d6d1f)

**Comment by tokitou-san** [comment]
Okay, seems not good. but like I said before I dont see the issue in my end. so:

1. You need to debug this yourself.
2. Or change the logic without using `snap-center`, Use JS for aligning perfect center.

**Comment by baseplate-admin** [comment]
> Okay, seems not good. but like I said before I dont see the issue in my end.

Try it on the 2nd last element?

**Comment by baseplate-admin** [comment]
[screen-recorder-thu-aug-31-2023-12-51-54.webm](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/24e15006-a99f-4c4b-85bd-6a1ad6fd3f6e)


Actually this whole implementation looks finicky

**Comment by tokitou-san** [comment]
Yea? then we need to use the 2nd method of
https://github.com/tokitou-san/CoreProject-V3-UI/issues/660#issuecomment-1700018674
