### ISSUE TITLE
Do not use `line_clamp`

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#675]
https://github.com/tokitou-san/CoreProject-V3-UI/blob/fb4161940e45b08aa7998b365779d1f82c3c3a0c/src/lib/components/shared/hover_expand.svelte#L9

https://github.com/tokitou-san/CoreProject-V3-UI/blob/fb4161940e45b08aa7998b365779d1f82c3c3a0c/src/lib/components/shared/hover_expand.svelte#L13

**Comment by baseplate-admin** [comment]
If you need these, pass as class

**Comment by tokitou-san** [comment]
> pass as class

Like `duration`? or in `class`?

**Comment by baseplate-admin** [comment]
> Like duration? or in class?

`line-clamp-1`

**Comment by tokitou-san** [comment]
> line-clamp-1

uhh I meant, do we need to export something like this
```js
export let line_clamp = "";
```
or inside `klass`? like
```html
<HoverExpand class="line-clamp-1"></HoverExpand>
```

**Comment by baseplate-admin** [comment]
> or inside klass? like

This
