### ISSUE TITLE
Refractor it for tailwind?

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#677]
https://github.com/tokitou-san/CoreProject-V3-UI/blob/fb4161940e45b08aa7998b365779d1f82c3c3a0c/src/lib/components/shared/scroll_area.svelte#L38-L67

**Comment by tokitou-san** [comment]
Okay, but we need to do something with `mask-image`
https://www.npmjs.com/package/tailwind-gradient-mask-image

**Comment by baseplate-admin** [comment]
> Okay, but we need to do something with mask-image

yes use arbitrary values

**Comment by tokitou-san** [comment]
>arbitrary values

Sure? loooooong class :\
anyways lets see if it looks off, if so we need to use something like I mentioned above
