### ISSUE TITLE
What's the point of this file?

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#678]
https://github.com/tokitou-san/CoreProject-V3-UI/blob/fb4161940e45b08aa7998b365779d1f82c3c3a0c/src/index.test.ts

**Comment by tokitou-san** [comment]
> https://github.com/tokitou-san/CoreProject-V3-UI/blob/fb4161940e45b08aa7998b365779d1f82c3c3a0c/src/index.test.ts

Like I added this test case lol.
remove it?

**Comment by baseplate-admin** [comment]
> Like I added this test case lol.

tattoo is accepting his mistakes

**Comment by tokitou-san** [comment]
> tattoo is accepting his mistakes

No its not mine, sveltekit generated
