### ISSUE TITLE
Constructing inline class is not a good idea. 

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#679]
https://github.com/tokitou-san/CoreProject-V3-UI/blob/fb4161940e45b08aa7998b365779d1f82c3c3a0c/src/lib/components/pages/home/latest_episodes_card.svelte#L94

```svelte

<script>
var classs = new TattooSucks('Tattoo is actually weird');
</script>

<>{classs}</>
```

**Comment by tokitou-san** [comment]
> var classs, <>{classs}</>

Owwh! sheldon still in react :\
and using sucking `var` :hankey:
